# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Fireball Docs
subtitle:
description: Html5 Game Engine for the Future.
author: Fireball Developers
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://docs.fireball-x.com
root: /
permalink: :permalinks/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
yuidoc_dir: api
tag_dir: tags
archive_dir: archives
category_dir: /
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: page
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  tab_replace: '  '

# Category & Tag
default_category: manual
category_map: manual,tutorial,developer,api
exclude_generators: index

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: fireball

# Feed
feed:
    type: atom
    path: atom.xml
    limit: 200

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:fireball-x/docs-en.git
  branch: gh-pages
  message: "Updated site [ci skip]"
